plugins {
    id "com.android.application"
}

android {
    namespace "br.com.pelegobox.radio"
    compileSdk 35

    defaultConfig {
        applicationId "br.com.pelegobox.radio.teste548"
        minSdk 21
        targetSdk 33
        versionCode 548
        versionName "5.4.8-layout-mobile-r2"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
