<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>PELEGO.ScreenInk</AssemblyName>
    <RootNamespace>PelegoMarkerV2</RootNamespace>
    <Version>2.9.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>pelego.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="TimerAlias.cs" />
    <Compile Include="ProgramV29.cs" />
  </ItemGroup>
</Project>
